"""empty message

Revision ID: 3c83a80c0d8e
Revises: 96defece6d41
Create Date: 2025-07-17 17:26:01.987836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c83a80c0d8e'
down_revision = '96defece6d41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('people_favorites')
    op.drop_table('planets_favorites')
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('people_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'planets', ['planet_id'], ['id'])
        batch_op.create_foreign_key(None, 'people', ['people_id'], ['id'])

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('population',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('population',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('people_id')
        batch_op.drop_column('planet_id')

    op.create_table('planets_favorites',
    sa.Column('planets_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('favorites_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['favorites_id'], ['favorites.id'], name='planets_favorites_favorites_id_fkey'),
    sa.ForeignKeyConstraint(['planets_id'], ['planets.id'], name='planets_favorites_planets_id_fkey')
    )
    op.create_table('people_favorites',
    sa.Column('people_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('favorites_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['favorites_id'], ['favorites.id'], name='people_favorites_favorites_id_fkey'),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], name='people_favorites_people_id_fkey')
    )
    # ### end Alembic commands ###
